### ISSUE TITLE
Add GHA for linting 

### ISSUE THREAD

**Issue by edmundcwm** [PatelUtkarsh/better-file-name-ai#25]

**Comment by PatelUtkarsh** [comment]
Hello @edmundcwm, 

We do have linting for example https://github.com/PatelUtkarsh/better-file-name-ai/actions/runs/8671676380 

Are you referring to anything in particular within linting?

**Comment by edmundcwm** [comment]
I must have mistakenly created this issue (and #24 and #23). I believe it's meant for another repo 😅. Sorry for the confusion! 🤦‍♂️
